name: linuxdo-daily-check-in

on:
  schedule:
    - cron: '0 0 * * *'  # 每天0点 UTC 时间执行
  workflow_dispatch:

jobs:
  run_script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9.19'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          playwright install chromium

      - name: Debug info
        run: |
          echo "Python version:"
          python --version
          echo "Pip version:"
          pip --version
          echo "Installed packages:"
          pip list

      - name: Execute script
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          python -u main.py
        
      - name: Check for errors
        if: failure()
        run: |
          echo "Script execution failed. Checking for error logs..."
          if [ -f error.log ]; then
            cat error.log
          else
            echo "No error log found."
          fi